### ISSUE TITLE
Validate ACL policy

### ISSUE THREAD

**Issue by wcooley** [puppet-community/puppet-rundeck#103]
Given the complicated structure of the `$acl_policies` parameter of `rundeck::config::aclpolicyfile`, it would also be nice to see validation of a minimal policy hash. (Determining what that minimum is, of course, is possibly the more complicated problem.)

**Comment by liamjbennett** [comment]
Yea +1 for this

**Comment by liamjbennett** [comment]
I think the best option for this is to write a custom validate function for the acl hash. I am going to give that a go and see what I can come up with.

**Comment by liamjbennett** [comment]
Started work on this on the validate_acl branch.
