### ISSUE TITLE
Project define doesn't have ssh_keypath parameter

### ISSUE THREAD

**Issue by clauded** [puppet-community/puppet-rundeck#118]
In puppet-rundeck/manifests/config/project.pp, documentation mention the 'ssh_keypath' parameter, however it's not defined as a parameter but only as a variable. So if we call the module with 'ssh_keypath', puppet run fails.

**Comment by jyaworski** [comment]
Hello:

This should be fixed by #153.

**Comment by ltutar** [comment]
I just downloaded the master. It is working. Thank you very much.
