### ISSUE TITLE
Error on rundeck::facts crashing old puppetdb

### ISSUE THREAD

**Issue by Tombar** [puppet-community/puppet-rundeck#132]
Hello Guys, congrats on the puppet-comunity effort! 

This bug has haunted me for almost a week! hope I can save some souls :)

The main issue is, the facter code itself is plain wrong @debian7 at least

```ruby
# Fact: rundeck_version
#
# Purpose: Return facts for the running version of rundeck.
#
if File.exists?('/etc/debian_version')
  version = %["dpkg-query -W -f 'rundeck_version=${Version}\n' rundeck"]
  puts version
elsif File.exists?('/etc/redhat-release') or File.exists?('/etc/centos-release')
  version = %["rpm -q --qf 'rundeck_version=%{VERSION}\n' rundeck"]
  puts version
```

Will output: 
```bash
root@deployer:/etc/facter/facts.d# ./rundeck_facts.rb
"dpkg-query -W -f 'rundeck_version=${Version}
' rundeck"
```

The side effect is, at least on my environments it managed to crash the replace_facts stage at puppetdb > https://tickets.puppetlabs.com/browse/PDB-2034 with really unfortunately consecuences.

Fortunately its plain easy to disable rundeck::facts from hiera :) 

Last but not least, all this happens to me using 587c9192bd67468d7cd28aff2b3be51281e409cf since i'm stuck with #125 

Regards

M

**Comment by jbehrends** [comment]
This also effects the latest puppetdb v3.1.0 and will result in puppetdb eventually running out of disk or store space.

**Comment by liamjbennett** [comment]
This has been resolved by @jbehrends. Thanks for the PR.
