### ISSUE TITLE
Build fails, so no commits to forge.puppetlabs.com

### ISSUE THREAD

**Issue by robertdebock** [puppet-community/puppet-rundeck#36]
I noticed the build has been failing the last 3 months or so (https://travis-ci.org/opentable/puppet-rundeck/builds) and the code on forge.puppetlabs.com is outdated. In my case (CentOS) it's not working anymore because of a specific jre that's not available (anymore?).

Part of params.pp
```
    'RedHat', 'Amazon': {
      $package_name = 'rundeck'
      $package_version = '2.0.3-1.14.GA'
      $package_ensure = 'installed'
      $service_name = 'rundeckd'
      $jre_name = 'java-1.6.0-openjdk'
      $jre_version = '1.6.0.0-1.66.1.13.0.el6'
    }
```
Output of yum info java-1.6.0-openjdk
```
Name        : java-1.6.0-openjdk
Arch        : x86_64
Epoch       : 1
Version     : 1.6.0.34
Release     : 1.13.6.1.el6_6
```

**Comment by liamjbennett** [comment]
Sorry this took so long to be looked at. I am closing this issue now in favour of #48 where there is a little bit of discussion of how best to address this problem.
