### ISSUE TITLE
rundeck url change to http://localhost:4440

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#40]
I successfully set the puppet code (release 1.0) within vagrant. I can login via `http://192.168.1.2:4440/user/login` from my laptop, created some projects and jobs and save the setting. 

Today I saw the new release (1.1) announced, did `git pull`, and `vagrant reload --provision`. I still can see the login page, but when I try to login with `Google Chrome`, it stays at login page. When I login with `Safari`, the URL is changed to `http://localhost:4440/menu/home` and no content is displayed.

```
# pwd
/etc/rundeck
# grep "example.com"  *
framework.properties:framework.server.hostname = rundeck.example.com
framework.properties:framework.server.name = rundeck.example.com
framework.properties:framework.server.url = http://rundeck.example.com:4440
rundeck-config.properties:grails.serverURL=http://rundeck.example.com:4440
```

Any thing I need adjust?

**Comment by SydOps** [comment]
https://github.com/rundeck/rundeck/issues/671

**Comment by Joginder22** [comment]
Hi 
Using SydOps's instruction trick worked though but now log output is not showing on rundeck. after debugging rundeck shows the error on commenting #grails.serverURL i.e gails.serverURL not set. 

However, while changing the port 4440 back to my nat port works flawless.
