### ISSUE TITLE
Fact rundeck_version is not OS aware

### ISSUE THREAD

**Issue by robertdebock** [puppet-community/puppet-rundeck#41]
The file rundeck/files/rundeck_version is not OS aware. It contains a reference to dpkg, but not rpm.

Maybe it's possible to use the resource abstraction layer from puppet to figure out the version:
```
$ puppet resource package rundeck
package { 'rundeck':
  ensure => '2.4.2-1.3.GA',
}
```

I'll make a fork, patch and pull request in a moment.

**Comment by liamjbennett** [comment]
Fixed in 4312884a6642eace0db6167f6d8267d96e19c3aa
