### ISSUE TITLE
package_version and package_source (baseurl) are not supported for Redhat/CentOS.

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#43]
I need install old version, so I updated my hiera yaml file as below, 

```
rundeck::package_version: '1.6.2-1.GA'
rundeck::package_ensure: present
```

It didn't work. Then I review the `manifests/install.pp` code, and found it didn't support properly for  `Redhat/centOS`.  it have hard-coding to install latest rundeck version and only from di.bintray.com, there is no chance you can choice the version and baseurl (package_source)

Second, there is no version 1.6 you can download from `dl.bintray.com` , lowest version is 2.0.

```
    'RedHat': {
      if $manage_yum_repo == true {
        yumrepo { 'bintray-rundeck':
          baseurl  => 'http://dl.bintray.com/rundeck/rundeck-rpm/',
          descr    => 'bintray rundeck repo',
          enabled  => '1',
          gpgcheck => '0',
          priority => '1',
          before   => Package['rundeck'],
        }
      }

      ensure_resource('package', 'rundeck', {'ensure' => $package_ensure} )
    }
```

**Comment by SydOps** [comment]
@liamjbennett any options for this issue?

**Comment by liamjbennett** [comment]
The solution here is to re-implement the same download functionality that we have for Debian. It was there when I first wrote the module but then we moved to the package repo when I discovered its existence.

**Comment by SydOps** [comment]
@liamjbennett will we get update in redhat/centos for my issue?

**Comment by liamjbennett** [comment]
Yes, I will be working on this in the next day or so

**Comment by SydOps** [comment]
My system (centos) find the latest version

```
[root@rundeck log]# yum list |grep rundeck
rundeck.noarch                  2.5.0-1.6.GA    @bintray-rundeck
rundeck-config.noarch           2.5.0-1.6.GA    @bintray-rundeck
rundeck.noarch                  2.5.1-1.7.GA    bintray-rundeck
rundeck-config.noarch           2.5.1-1.7.GA    bintray-rundeck
```

I will work out the puppet code to get the nominate version  `2.5.1-1.7.GA` to be installed and raise a pull request. 

Ta

**Comment by SydOps** [comment]
Finally I work it out. `rundeck::package_version` is useless for centos, so define the version in rundeck::package_ensure is enough.

    rundeck::package_ensure: '2.5.1-1.7.GA'

And I got the updates:

    Notice: /Stage[main]/Rundeck::Install/Package[rundeck]/ensure: ensure changed '2.5.0-1.6.GA' to '2.5.1-1.7.GA'

**Comment by SydOps** [comment]
Fix the `service is not restarted` issue, will follow with a pull request.

{noformat}
Notice: /Stage[main]/Rundeck::Install/Package[rundeck]/ensure: ensure changed '2.5.0-1.6.GA' to '2.5.1-1.7.GA'
Info: /Stage[main]/Rundeck::Install/Package[rundeck]: Scheduling refresh of Class[Rundeck::Service]
Info: Class[Rundeck::Service]: Scheduling refresh of Service[rundeckd]
Notice: /Stage[main]/Rundeck::Service/Service[rundeckd]: Triggered 'refresh' from 1 events
{noformat}

Here is the change in *manifests/install.pp*

          ensure_resource('package', 'rundeck', {'ensure' => $package_ensure, notify => Class['rundeck::service'] } )

**Comment by SydOps** [comment]
commit `cdd41e5` is raised to fix issue `rundeck service is not restarted after upgraded in CentOS`
commit `03e714d` is raised to fix issue `package rundeck_config is not upgraded to same version after rundeck is upgraded in CentOS`

**Comment by SydOps** [comment]
Pull request is https://github.com/puppet-community/puppet-rundeck/pull/69

Please review and merge it. I am waiting the new release 2.5.1 to be upgraded in our system and depend on this change. 

Thanks a lot.
