### ISSUE TITLE
use ${pd} variable to replace /var/lib/rundeck/libext, if not default value

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#79]
Hi

Find this issue when change default plugin directory, and the unless command ls + grep can be merged into one ls command.

Change plugin.pp from:

    unless  => "/bin/ls -l /var/lib/rundeck/libext/ | grep ${name}"

to

    unless  => "/bin/ls ${pd}/${name} 2>/dev/null"

the change has been tested with updated code.
```
Debug: Exec[download plugin rundeck-ec2-nodes-plugin-1.5.jar](provider=posix): Executing check '/bin/ls /var/lib/rundeck/libext/rundeck-ec2-nodes-plugin-1.5.jar 2>/dev/null'
Debug: Executing '/bin/ls /var/lib/rundeck/libext/rundeck-ec2-nodes-plugin-1.5.jar 2>/dev/null'
Debug: /Stage[main]/Role::Rundeck/Rundeck::Config::Plugin[rundeck-ec2-nodes-plugin]/Exec[download plugin rundeck-ec2-nodes-plugin-1.5.jar]/unless: /var/lib/rundeck/libext/rundeck-ec2-nodes-plugin-1.5.jar
```

**Comment by SydOps** [comment]
Pull request has been raised https://github.com/puppet-community/puppet-rundeck/pull/80

**Comment by liamjbennett** [comment]
This issue should now have been resolved.
