### ISSUE TITLE
params list are huge now, no instruction on how to use them properly.

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#82]
@liamjbennett 

Could you please share me a sample of hiera yaml file to list most params? I am stuck to set them properly, and waste a lot of time.

For example, how to setup:
```
auth_type
auth_config
plugin::name
plugin::source
```
If you can provide, issue #77 and #78 can be closed.

**Comment by liamjbennett** [comment]
```yaml
rundeck::auth_config:
  file:
    auth_users:
      - username: 'puppet'
        password: 'puppet'
        roles:
          - user
          - admin
          - architect
          - deploy
          - build
  active_directory:
    server: 'server-01.corp.company.com'
    bind_dn: 'CN=x,CN=Users,DC=corp,DC=company,DC=com'
    bind_password: 'notTheRealPassword'
    user_base_dn: 'DC=corp,DC=company,DC=com'
    role_base_dn: 'DC=corp,DC=company,DC=com'

**Comment by SydOps** [comment]
This works for me, thanks @liamjbennett 

Could you please provide the same for `rundeck::plugin::name` and `rundeck::plugin::source`?

Can you paste a total sample of hiera yaml file for future reference? it will save a lot of time for others who need to use this puppet module.

**Comment by liamjbennett** [comment]
Yes, the README does need further examples and I will keep this issue open until I have written some

**Comment by SydOps** [comment]
Thanks @liamjbennett, waiting for the updates.

**Comment by ltutar** [comment]
I am also not able to create a project through yaml. Can somebody provide an example? 'puppet module install' downloads version 1.2.0 on my machine.
I found the following in project.pp
# rundeck::config::project { 'test project':
#  ssh_keypath            => '/var/lib/rundeck/.ssh/id_rsa',
#  file_copier_provider   => 'jsch-scp',
#  node_executor_provider => 'jsch-ssh',
#  resource_sources       => $resource_hash
# }

**Comment by ltutar** [comment]
??

**Comment by igalic** [comment]
@ltutar `puppet module install` what?

**Comment by ltutar** [comment]
I just want to know why 
class rundeck_config::config {
   rundeck::config::project { 'PetClinicProject':
   }
}

works,
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/File[/var/rundeck/projects/PetClinicProject]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/File[/var/rundeck/projects/PetClinicProject/var]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/File[/var/rundeck/projects/PetClinicProject/etc]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/File[/var/rundeck/projects/PetClinicProject/etc/project.properties]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/Ini_setting[PetClinicProject::project.name]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/Ini_setting[PetClinicProject::project.ssh-authentication]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/Ini_setting[PetClinicProject::project.ssh-keypath]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/Ini_setting[PetClinicProject::service.FileCopier.default.provider]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/Ini_setting[PetClinicProject::service.NodeExecutor.default.provider]/ensure: created
Notice: /Stage[main]/Rundeck_config::Config/Rundeck::Config::Project[PetClinicProject]/Ini_setting[PetClinicProject::service.NodeExecutor.default.provider]/ensure: created
Notice: Applied catalog in 61.05 seconds

and through yaml as
rundeck::projects:
  testproject:

does not work.
Notice: /Stage[main]/Rundeck::Service/Service[rundeckd]/enable: enable changed 'false' to 'true'
Notice: /Stage[main]/Logstashforwarder::Service/Logstashforwarder::Service::Init[logstash-forwarder]/Service[logstash-forwarder]/enable: enable changed 'false' to 'true'
Notice: Applied catalog in 1.02 seconds

**Comment by jyaworski** [comment]
@ltutar hi! This is because each project needs to be a hash at this time. This line shows the logic:

https://github.com/puppet-community/puppet-rundeck/blob/master/manifests/config.pp#L155

You could try the following:

````yaml
rundeck::projects:
  testproject: {}
````

I am also not sure when the last time we had a forge release. Have you tried the git version?

**Comment by ltutar** [comment]
yaml with version 1.2.0 does not work.
root@puppetmaster modules]# puppet module install puppet-rundeck
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ puppet-rundeck (v1.2.0)
  ├── puppetlabs-inifile (v1.4.2)
  └── puppetlabs-stdlib (v4.9.0)
[root@puppetmaster modules]# puppet module upgrade puppet-rundeck
Notice: Preparing to upgrade 'puppet-rundeck' ...
Notice: Found 'puppet-rundeck' (v1.2.0) in /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not upgrade module 'puppet-rundeck' (v1.2.0 -> latest)
  There are 1 newer versions
    No combination of dependency upgrades would satisfy all dependencies
    Dependencies will not be automatically upgraded across major versions
    Upgrading one or more of these modules may permit the upgrade to succeed:
    - puppetlabs-stdlib
    - puppetlabs-inifile
    Use `puppet module upgrade --force` to upgrade only this module
[root@puppetmaster modules]# puppet --version
4.2.2
[root@puppetmaster modules]# 

I am working on to get version 2.0.0 running.

[root@rundeckagent ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/validate_rd_policy: no such file to load -- puppet/util/rundeck_acl at /etc/puppetlabs/code/environments/production/modules/rundeck/manifests/init.pp:181:3 on node rundeckagent.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
[root@rundeckagent ~]#

**Comment by ltutar** [comment]
v2.0.0 will also not create the project.

**Comment by jyaworski** [comment]
@ltutar can you paste your modified YAML block?

@liamjbennett we really need to solve the function loading thing. :/ One of those PRs should get accepted.

**Comment by ltutar** [comment]
rundeck::package_ensure: '2.6.1-1.12.GA'
rundeck::auth_config:
  file:
    admin_user:   'admin'
    admin_password: 'benny'
rundeck::framework_config:
  framework.server.password: 'benny'

rundeck::projects:
  testproject: {}

**Comment by jyaworski** [comment]
@ltutar did you lose formatting? Could you either wrap your output in the code example from here?

https://guides.github.com/features/mastering-markdown/

If it's just not doing anything, the chances are that you need to use the git version, as the feature was added fairly recently.

**Comment by ltutar** [comment]
Just installed the latest git version on a new created puppet master :(
[root@rundeckagent ~]# puppet --version
4.2.3
[root@rundeckagent ~]# 


Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Could not autoload puppet/parser/functions/validate_rd_policy: no such file to load -- puppet/util/rundeck_acl at /etc/puppetlabs/code/environments/production/modules/rundeck/manifests/init.pp:181:3 on node rundeckagent.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by ltutar** [comment]
Downloading the latest git version made the following yaml work. Thank you all for your help

**Comment by ltutar** [comment]
Can somebody help me to yaml the following?
```
  rundeck::config::project { 'PetClinicProject':
    resource_sources => {
      'PetClinicProject' => {
        project_name        => 'PetClinicProject',
        source_type         => 'directory',
        directory           => '/opt/rundeck/nodes',
        include_server_node => false,
        resource_format     => 'resourcejson',
      }
    }
  }
```

**Comment by jyaworski** [comment]
@ltutar github is not designed for this kind of question. I would try StackOverflow in the future.

You may also want to look at this link:

https://docs.puppetlabs.com/hiera/1/complete_example.html#kermitexamplecomyaml

**Comment by ltutar** [comment]
Ok.

**Comment by jyaworski** [comment]
@liamjbennett is this issue solved? Can it be closed?

**Comment by ltutar** [comment]
I still do not have the answer for yaml. But as I am told github is not the place for these kind of questions, the issue may be closed.

**Comment by SydOps** [comment]
@liamjbennett 

Do you think I can close this ticket? You marked it with enhancement label on May 29, and I am still waiting the updates.

**Comment by ltutar** [comment]
I now have the yaml file. I will post it here  for the other users.
```
  rundeck::config::project { 'PetClinicProject':
    ssh_keypath             => '/opt/rundeck/key/insecure_private_key',
    resource_sources => {
      'PetClinicProject' => {
        project_name        => 'PetClinicProject',
        source_type         => 'directory',
        directory           => '/opt/rundeck',
        include_server_node => false,
        resource_format     => 'resourcejson',
      }
    }
  }
```

```
rundeck::projects:
  PetClinicProject:
    ssh_keypath: '/opt/rundeck/key/insecure_private_key'
    resource_sources:
      PetClinicProject:
        project_name: 'PetClinicProject'
        source_type: 'directory'
        directory: '/opt/rundeck'
        include_server_node: false
        resource_format: 'resourcejson'
```

**Comment by SydOps** [comment]
@ltutar :+1: thanks for sharing.
