### ISSUE TITLE
rd-jobs is failed after change admin password

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#87]
report the issue to rundeck with https://github.com/rundeck/rundeck/issues/1268

I found the reason, so it need be fixed in puppet-rundeck. 

When change the admin password in `/etc/rundeck/realm.properties`, the password in `/etc/rundeck/framework.properties` is not changed. Then `rd-jobs` command is failed.

Could you please add new feature to update the admin password at same time in both  `/etc/rundeck/realm.properties` and `/etc/rundeck/framework.properties` ?

**Comment by SydOps** [comment]
Ok, I fixed my own issue, here is the updates in hiera yaml file
```
rundeck::auth_config:
  file:
    admin_user:   'admin'
    admin_password: 'new_password'

rundeck::framework_config:
  framework.server.password: 'new_password'
```

**Comment by liamjbennett** [comment]
Well I'm glad you managed to resolve your issue. This does however demonstrate a bad user experience and how easy it is mess up the configuration. You're correct to close this particular ticket but I may raise an additional one later on to deal with this problem more generically.

I think there should probably be some validation around hashes that we input for these files.
