### ISSUE TITLE
doesn't have ldaps support

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#93]
I set with ldaps, but didn't get what I need. After review the code, i found the setting in `_auth_ldap.erb` are only for `ldap`, not for `ldaps`

**Comment by wcooley** [comment]
@SydOps Did you notice that you can specify the LDAP URL instead of the server and port? I added this with PR #61 so you can specify *ldaps*.

**Comment by SydOps** [comment]
Thanks, @wcooley 

That's in new commits! My environment is locked with `Puppetfile.lock` file.

Sure, will adjust to use latest code and try again.

**Comment by liamjbennett** [comment]
I think we can say that this is just a poor examples/documentation problem. Will close for now.
