### ISSUE TITLE
ldap template typo

### ISSUE THREAD

**Issue by rooty0** [puppet-community/puppet-rundeck#96]
I think this is a typo:
```
...
bindDn="<%= @auth_config['ldap']['bind_dn']%>,<%= @auth_config['ldap']['user_base_dn'] %>"
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
userBaseDn="<%= @auth_config['ldap']['user_base_dn'] %>"
```
According to official documentation:
```
....
bindDn="cn=Manager,dc=example,dc=com"
...
userBaseDn="ou=People,dc=test1,dc=example,dc=com"
```
 it's breaking ldap authentication

please merge following to fix this

**Comment by SydOps** [comment]
I already raised the issue in #84 to report the same issue.

**Comment by rooty0** [comment]
@SydOps thanks, just noticed
I don't really understand how that fix https://github.com/puppet-community/puppet-rundeck/commit/57dd07315844a499e832c26ebb3b60d228828ab1 will solve this (and yours) issue
